name: Deploy Flask App

on:
  push:
    branches:
      - main
    paths:
      - "app.py"
      - "requirements.txt"
      - "Dockerfile"
      - "k8s/**"
      - "terraform/**"

jobs:
  # Job 1: Build and Push Docker Image
  build-docker:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Step 2: Set up Python and Install Dependencies
    - name: Set up Python and install dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 4: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/docker-flask-app:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

  # Job 2: Run Terraform
  terraform:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Run Terraform
    - name: Run Terraform
      run: |
        terraform --version  
        terraform init
        terraform apply -auto-approve
      working-directory: terraform

  # Job 3: Push Terraform State Back to GitHub
  push-terraform-state:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Commit and Push Terraform State
    - name: Commit and Push Terraform State
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        cd terraform
        git add *
        if git diff --cached --quiet; then
          echo "No changes in Terraform state to commit."
         else
            git commit -m "Update Terraform state"
            git push
          fi
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}